trigger:
  - main

pool:
  vmImage: 'macOS-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>=2.7'

  - script: sudo gem install cocoapods
    displayName: 'Install CocoaPods'

  - script: pod install
    displayName: 'Install CocoaPods Dependencies'
    workingDirectory: '$(Build.SourcesDirectory)'

  - task: Xcode@5
    inputs:
      actions: 'build'
      configuration: '$(buildConfiguration)'
      sdk: 'iphoneos'
      xcWorkspacePath: '$(Build.SourcesDirectory)/testing_demo.xcodeproj/project.xcworkspace'
      scheme: 'testing_demo'
      packageApp: false

  - task: CopyFiles@2
    inputs:
      Contents: '**/*.ipa'
      TargetFolder: '$(build.artifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
