trigger:
  - master

pool:
  vmImage: 'macOS-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>=2.7'

  - script: sudo gem install cocoapods
    displayName: 'Install CocoaPods'

  - script: pod install --repo-update
    displayName: 'Install CocoaPods Dependencies'
    workingDirectory: '$(Build.SourcesDirectory)'

  - task: Xcode@5
    inputs:
      actions: 'clean archive'
      configuration: '$(buildConfiguration)'
      sdk: 'iphoneos'
      scheme: 'testing_demo'
      packageApp: true
      xcWorkspacePath: '$(Build.SourcesDirectory)/testing_demo.xcworkspace'
      archivePath: '$(build.artifactStagingDirectory)/testing_demo.xcarchive'
      exportPath: '$(build.artifactStagingDirectory)/output'
      exportOptions: 'plist'
      exportOptionsPlist: '$(Build.SourcesDirectory)/ExportOptions.plist'
      args: 'CODE_SIGNING_ALLOWED=NO'

  - task: CopyFiles@2
    inputs:
      contents: '$(build.artifactStagingDirectory)/output/*.ipa'
      targetFolder: '$(build.artifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(build.artifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
