trigger:
  - master

pool:
  vmImage: 'macOS-latest'

variables:
  buildConfiguration: 'Release'
  teamID: 'YOUR_TEAM_ID'  # Replace with your actual Apple Developer Team ID

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>=2.7'

  - script: sudo gem install cocoapods
    displayName: 'Install CocoaPods'

  - script: pod install --repo-update
    displayName: 'Install CocoaPods Dependencies'
    workingDirectory: '$(Build.SourcesDirectory)'

  - script: |
      cat <<EOF > $(Build.SourcesDirectory)/ExportOptions.plist
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
          <key>method</key>
          <string>app-store</string>
          <key>teamID</key>
          <string>$(teamID)</string>
          <key>uploadBitcode</key>
          <false/>
          <key>compileBitcode</key>
          <true/>
          <key>signingStyle</key>
          <string>automatic</string>
          <key>stripSwiftSymbols</key>
          <true/>
          <key>thinning</key>
          <string>&lt;none&gt;</string>
      </dict>
      </plist>
      EOF
    displayName: 'Create ExportOptions.plist'

  - task: Xcode@5
    inputs:
      actions: 'clean archive'
      configuration: '$(buildConfiguration)'
      sdk: 'iphoneos'
      scheme: 'testing_demo'
      packageApp: true
      xcWorkspacePath: '$(Build.SourcesDirectory)/testing_demo.xcworkspace'
      archivePath: '$(build.artifactStagingDirectory)/testing_demo.xcarchive'
      exportPath: '$(build.artifactStagingDirectory)/output'
      exportOptionsPlist: '$(Build.SourcesDirectory)/ExportOptions.plist'
      args: 'CODE_SIGNING_ALLOWED=NO'

  - task: CopyFiles@2
    inputs:
      contents: '$(build.artifactStagingDirectory)/output/*.ipa'
      targetFolder: '$(build.artifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(build.artifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
